In [83]:
import torch
import numpy as np

### 텐서 계산

#### 덧셈

In [46]:
m1 = torch.FloatTensor([[3,3]])
m2 = torch.FloatTensor([[2,2]])

In [47]:
m1+m2

tensor([[5., 5.]])

In [48]:
m1 = torch.FloatTensor([[1,3]])
m2 = torch.FloatTensor([3])

In [49]:
m1+m2 # 브로드케스팅됨

tensor([[4., 6.]])

#### 곱셈

In [35]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])

In [38]:
m1

tensor([[1., 2.],
        [3., 4.]])

In [39]:
m2

tensor([[1.],
        [2.]])

In [37]:
print(m1.matmul(m2)) # 행렬의 곱

tensor([[ 5.],
        [11.]])


In [40]:
print(m1.mul(m2)) # 원소끼리 곱

tensor([[1., 2.],
        [6., 8.]])


#### 평균

In [41]:
t = torch.FloatTensor([[1, 2], [3, 4]])

In [54]:
t

tensor([[1., 2.],
        [3., 4.]])

In [51]:
t.mean() # 4개 원소의 전체평균

tensor(2.5000)

In [55]:
print(t.mean(dim=0)) # 열방향 평균 ㅣ

tensor([2., 3.])


In [57]:
print(t.mean(dim=1)) # 행방향 평균 -

tensor([1.5000, 3.5000])


#### 합계 

In [59]:
t = torch.FloatTensor([[1, 2], [3, 4]])
t

tensor([[1., 2.],
        [3., 4.]])

In [60]:
t.sum() # 전체원소 합

tensor(10.)

In [61]:
t.sum(dim=0) # 열방향 합 ㅣ

tensor([4., 6.])

In [63]:
t.sum(dim=1) # 행방향 합 -

tensor([3., 7.])

#### 최대

In [73]:
t = torch.FloatTensor([[8, 2], [3, 4]])
t

tensor([[8., 2.],
        [3., 4.]])

In [74]:
t.max() # 전체중 최대

tensor(8.)

In [78]:
t.argmax() # argmax 가장 큰 원소의 인덱스 

tensor(0)

In [80]:
t.argmax(dim=0) # 각 행별로 argmax 가장 큰 원소의 인덱스 

tensor([0, 1])

### View == reshape

In [84]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)

In [87]:
print(ft)
print(ft.shape)

tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]])
torch.Size([2, 2, 3])


In [92]:
print(ft.view([-1,3]))
print(ft.view([-1,3]).size())

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


### Squeeze : 1인 차원 제거

In [93]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)


tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [94]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


### Unsqueeze : 특정 위치에 1인 차원을 추가

In [106]:
ft = torch.Tensor([[0, 1, 2],[3,4,5]])
print(ft)
print(ft.shape)

tensor([[0., 1., 2.],
        [3., 4., 5.]])
torch.Size([2, 3])


In [107]:
print(ft.unsqueeze(0)) # 0번째 차원에 1 추가
print(ft.unsqueeze(0).shape)

tensor([[[0., 1., 2.],
         [3., 4., 5.]]])
torch.Size([1, 2, 3])


In [108]:
print(ft.unsqueeze(1)) # 1번째 차원에 1 추가
print(ft.unsqueeze(1).shape)

tensor([[[0., 1., 2.]],

        [[3., 4., 5.]]])
torch.Size([2, 1, 3])


In [109]:
print(ft.unsqueeze(2)) # 2번째 차원에 1 추가
print(ft.unsqueeze(2).shape)

tensor([[[0.],
         [1.],
         [2.]],

        [[3.],
         [4.],
         [5.]]])
torch.Size([2, 3, 1])


### 타입변환

In [111]:
t = torch.LongTensor([1, 2, 3, 4]) # 정수형

In [115]:
x = t.float() # 실수형으로 변환
x 

tensor([1., 2., 3., 4.])

In [116]:
x.long() # 정수형으로 변환

tensor([1, 2, 3, 4])

In [119]:
t2 = torch.ByteTensor([True, False, False, True]) 
t2

tensor([1, 0, 0, 1], dtype=torch.uint8)

### 연결

#### cat

In [132]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])

In [133]:
print(torch.cat([x, y], dim=0)) # 행방향으로 추가 ㅣ
print(torch.cat([x, y], dim=0).size()) 

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
torch.Size([4, 2])


In [134]:
print(torch.cat([x, y], dim=1)) # 열방향으로 추가 -

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


#### Stacking

In [135]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

In [136]:
print(torch.stack([x, y, z]))
print(torch.stack([x, y, z]).size()) # 차원이 증가

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
torch.Size([3, 2])


In [138]:
# cat과 stacking의 차원 비교 
print(torch.cat([x, y, z], dim=0))
print(torch.cat([x, y, z], dim=0).size()) 

tensor([1., 4., 2., 5., 3., 6.])
torch.Size([6])


### ones_like / zeros_like

In [144]:
s = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(s)
print(s.size())

tensor([[0., 1., 2.],
        [2., 1., 0.]])
torch.Size([2, 3])


In [146]:
print(torch.ones_like(s))
print(torch.ones_like(s).size())

tensor([[1., 1., 1.],
        [1., 1., 1.]])
torch.Size([2, 3])


In [147]:
print(torch.zeros_like(s))
print(torch.zeros_like(s).size())

tensor([[0., 0., 0.],
        [0., 0., 0.]])
torch.Size([2, 3])
